services:

  mysql:
    image: mysql:8.0
    container_name: hotel-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_manager
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: hotel_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hotel-manager-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: always

  backend:
    build:
      context: ./backend
    container_name: hotel-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hotel_manager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: hotel-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data: