apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: cm9vdA==
  GOOGLE_CLIENT_SECRET: R09DU1BYLWZpWlJwY0pXdkFvUmdXWDBZQUtlYVBiNld2WmM=
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1taW4tMzItY2hhcnM=